AWSTemplateFormatVersion: 2010-09-09
Description: >- 
  Lambda to parse and log doc-chucker sns messages to s3.

Transform:
- AWS::Serverless-2016-10-31

Parameters:

  Environment:
    Type: String
    Description: 'The environment to deploy to: dev, qa, prod, etc'

  SNSTopic:
    Type: String
    Description: The SNS Topic to subscribe to

  NotificationBucket:
    Type: String
    Description: The SNS Bucket to log to.

Resources:

  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SNS topic.
      Runtime: nodejs12.x
      Handler: src/lambda.handler
      Environment:
        Variables:
          bucketName: !Ref NotificationBucket
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Sub  arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopic}
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: !Ref NotificationBucket
